version: "3.9"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: virtumate-backend
    ports:
      - "4000:4000"
    env_file:
      - .env.production
    restart: always

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: /api
    container_name: virtumate-frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - api
    env_file:
      - .env.production
    restart: always
