
services:
  api:
    image: ghcr.io/dhruvp66572/virtumate-server:latest
    container_name: virtumate-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    restart: always

  web:
    image: ghcr.io/dhruvp66572/virtumate-client:latest
    container_name: virtumate-frontend
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always
